api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
     path('stanice', views.mapa_stanice, name='stanice'),
     path('linija/<int:pk>', views.mapa_linija, name='linija'),

]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('dodaj_stanicu', views.DodajStanicuView.as_view(), name = 'dodaj_stanicu'),
    path('stanice', views.StaniceView.as_view(), name = 'stanice'),
    path('dodaj_liniju', views.DodajLinijuView.as_view(), name='dodaj_liniju'),
    path('linije', views.LinijeView.as_view(), name='linije')
]

mapa/urls.py
from django.urls import path
from . import views

app_name = 'mapa'

urlpatterns = [
    path('', views.StaniceView.as_view(), name='prikaz_stanica'),
    path('linija/<int:pk>', views.mapa_linija_prikaz, name='prikaz_linije'),
    path('linija/dodaj', views.mapa_linija_dodaj, name='dodaj_liniju')
   
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import PocetnaView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls', namespace='app')),
    path('', PocetnaView.as_view(), name='pocetna'),
    path('mapa/', include('mapa.urls', namespace='mapa')),
    path('api/', include('api.urls', namespace='api'))

    
]

api/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models
from django.forms import ModelForm
from django.shortcuts import reverse


class Stanica(models.Model):
    naziv = models.CharField(max_length=200)
    opis = models.CharField(max_length=200)
    tacka = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.naziv}"

    def get_absolute_url(self):
        return reverse('app:stanice')

class Linija(models.Model):
    naziv=models.CharField(max_length=200)
  
    
    stanice = models.ManyToManyField(Stanica, related_name='stanica')
    
    def __str__ (self):
        return f"{self.naziv}"

    def get_absolute_url(self):
        return reverse('app:linije')

app/forms.py
from django import forms
from .models import Linija, Stanica

class LinijaModelForm(forms.ModelForm):
    class Meta:
        model = Linija
        fields = ['naziv', 'stanice']

    naziv = forms.CharField(widget=(forms.TextInput(attrs={'class':'form-control mb-5'})))
    
    stanice = forms.ModelMultipleChoiceField(
    queryset=Stanica.objects.all(),
    widget=forms.CheckboxSelectMultiple(attrs={'onchange':'checkboxes()'
    })
)

class StanicaModelForm(forms.ModelForm):
    class Meta:
        model = Stanica
        fields = ['naziv', 'opis', 'tacka']

    naziv = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class':'form-control'}))
    opis = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class':'form-control'}))
    tacka = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control'}))

mapa/forms.py
from django import forms
from app.models import Linija, Stanica

class DodajLinijuForm(forms.Form):
    naziv = forms.CharField(widget=(forms.TextInput(attrs={'class':'form-control mt-1 mb-1'})))
    stanice = forms.CharField(widget=(forms.TextInput(attrs={'class':'form-control mb-1', 'readonly':'true', 'style':'display:none'})))

api/views.py
from django.shortcuts import render
from app.models import Stanica, Linija
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
import json

# Create your views here.
def mapa_stanice(request):
     stanice = Stanica.objects.all()
     data = serializers.serialize('json',stanice)
     return HttpResponse(data, content_type='text/json')

def mapa_linija(request, pk):
    linija = Linija.objects.get(pk=pk)
    stanice = linija.stanice.all()
    data = serializers.serialize('json', stanice)
    return HttpResponse(data, content_type='text/json')

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .forms import LinijaModelForm, StanicaModelForm


from .models import Stanica, Linija

class PocetnaView(generic.TemplateView):
    template_name = 'app/pocetna.html'

class DodajStanicuView(generic.CreateView):
    template_name = 'app/dodaj_stanicu.html'
    form_class = StanicaModelForm    

class StaniceView(generic.ListView):
    template_name = 'app/stanice.html'
    model = Stanica
    context_object_name = 'lista_stanica'

class DodajLinijuView(generic.CreateView):
    template_name = 'app/dodaj_liniju.html'    
    form_class = LinijaModelForm

class LinijeView(generic.ListView):
    template_name = 'app/linije.html'
    model = Linija
    context_object_name = 'lista_linija'
   

    

mapa/views.py
from django.shortcuts import render, redirect, reverse

from app.models import Stanica, Linija
from django.http import HttpResponse
from django.views.generic import CreateView
from app.forms import StanicaModelForm, LinijaModelForm
from .forms import  DodajLinijuForm

class StaniceView(CreateView):
    template_name = 'mapa/index.html'
    form_class = StanicaModelForm
    def get_success_url(self):
        return reverse('mapa:prikaz_stanica')

def mapa_linija_prikaz(request, pk):
    linija = Linija.objects.get(pk=pk)    
    return render(request, 'mapa/linija.html', {'linija':linija, 'pk':pk})


class DodajLinijuView(CreateView):   
    template_name = 'mapa/dodaj_liniju.html'
    form_class = LinijaModelForm            
    
def mapa_linija_dodaj(request):
    if request.method == 'GET':
        form = DodajLinijuForm()
        return render(request, 'mapa/dodaj_liniju.html', {'form':form})
    elif request.method == 'POST':
        form = DodajLinijuForm(request.POST)
        if form.is_valid():
            naziv = form.cleaned_data['naziv']
            lista_stanica = [int(i) for i in list(form.cleaned_data['stanice'].split(','))]
            
            stanice = Stanica.objects.filter(pk__in=lista_stanica)
            
            linija = Linija.objects.create(naziv=naziv)
            for stanica in stanice.iterator():
                linija.stanice.add(stanica)
            return mapa_linija_prikaz(request,linija.pk)
            
            

app/templates/app/dodaj_liniju.html
{% extends 'app/layout.html' %}
{% load static %}


{% block body %}
    <form method="POST">
        {% csrf_token %}
        {% if stanice.all.count < 3  %}
        <a href="{% url 'app:dodaj_stanicu' %}" role="button">Dodaj najmanje 3 stanice</a>
        {% else %}

        {{ form.as_p }}
        {% endif %}
        <input type="submit" class="btn btn-primary w-100" id="sacuvaj" value="Sacuvaj liniju" disabled="true">
    </form>
    <script src="{% static 'app/index.js' %}"> 
		
	</script> 
    {% endblock %}
    
    

app/templates/app/dodaj_stanicu.html
{% extends 'app/layout.html' %}
{% block body %}
<div class="form-group">
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary w-100 mb-3" type="submit" value="Dodaj stanicu">

    </form>
</div>
{% endblock %}

app/templates/app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/style.css' %}">
    <link rel="stylesheet" href="{% static 'mapa/styles.css' %}">
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css">
    <title>Autobus</title>
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'pocetna' %}">Pocetna</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app:stanice' %}">Autobuske stanice</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'app:linije' %}">Autobuske linije</a>
              </li>
              
               
            </ul>
           
          </div>
        </div>
      </nav>
    
     <main>
        <div class="container-fluid">
            <div class="d-flex align-items-center py-5">
                <div class="col-12 col-md-6 col-lg-4 mx-auto">
                    {% block body %}
                    {% endblock  %}
                </div>
            </div>
        </div>
    </main>
    
</body>
</html>

app/templates/app/linije.html
{% extends 'app/layout.html' %}

{% block body %}
<h1>Dostupne autobuske linije</h1>

    
{% if lista_linija %}

<table class="table table-striped table-bordered">
    <tr>
        <th>Naziv</th>
        <th>Stanice</th>
     
    </tr>
    {% for linija in lista_linija %}
        <tr>    
             <td data-togle="tooltip" data-placement="top" title="Prikazi na mapi"><a href="{% url 'mapa:prikaz_linije' pk=linija.pk %}">{{ linija.naziv }}</a></td>  
          
            <td>
                
                {% for stanica in linija.stanice.all %}
               {{ stanica.naziv }}  
                {% if stanica != linija.stanice.last %}
                    ,
                    {%endif%}
                {% endfor %}                
            </td>          
        </tr>        
    {% endfor %}
</table>
{% else %}
<strong>Nema dostupnih linija</strong>
{% endif %}
<br>
<a class="btn btn-primary w-100" href="{% url 'app:dodaj_liniju' %}">Dodaj autobusku liniju</a>
<a class="btn btn-primary mt-2 w-100" href="{% url 'mapa:dodaj_liniju' %}">Izaberi na mapi</a>
{% endblock %}

app/templates/app/pocetna.html
{% extends 'app/layout.html' %}
{% block body %}
<ul>
    <li><a href="{% url 'app:stanice' %}">Autobuske stanice</a></li>
    <li><a href="{% url 'app:linije' %}">Autobuske linije</a></li>
</ul>
{% endblock %}

app/templates/app/stanice.html
{% extends 'app/layout.html' %}
{% block body %}
<h1>Dostupne autobuske stanice</h1>

    
    {% if lista_stanica %}
    <table class="table table-striped table-bordered">
        <tr>
            <th>Naziv</th>
            <th>Opis</th>
            <th>Lokacija</th>
        </tr>
        {% for stanica in lista_stanica %}
            <tr>    
                <td>{{stanica.naziv}}</td>  
                <td>{{stanica.opis}}</td>
                <td>{{stanica.tacka}}</td>
            </tr>        
        {% endfor %}

    </table>
    {% else %}
    <strong>Nema dostupnih stanica</strong>
    {%endif%}
<br>
<a href="{% url 'app:dodaj_stanicu' %}" class="btn btn-primary w-100 mb-3">Dodaj autobusku stanicu</a>
<a href="{% url 'mapa:prikaz_stanica' %}" class="btn btn-primary w-100 mb-3">Pogledaj stanice na mapi</a>
{% endblock %}

mapa/templates/mapa/dodaj_liniju.html
    {% extends 'app/layout.html' %}
    {% load static %}

    {% block body %}

    <h2>Izaberi minimalno 3 stanice na mapi</h2>
                
            <div id="js-map" class="map"></div>
           
            <form class="form-group" action="{% url 'mapa:dodaj_liniju' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input id="dodaj_liniju" value="Sacuvaj" type="submit" class="btn btn-primary w-auto">
            </form>
        
        
    
    <div id="popup" class="ol-popup">
        <a href="#" id="popup-closer" class="ol-popup-closer"></a>
        <div id="popup-content"></div>
    </div>
    <div class="overlay-container">
        <button class="btn btn-primary" id="chekirajStanicu">Dodaj</button><br>
        <span class="overlay-text" id="feature-name"></span><br>
        <span class="overlay-text" id="feature-additional-info"></span><br>

    </div>
    
    <script src="{% static 'mapa/main.js' %}"></script>
    <script>
        
      prikaziStanice('{% url "api:stanice" %}')
    
      uslov()
      
    </script>
{% endblock %}

mapa/templates/mapa/index.html
    {% extends 'app/layout.html' %}
    {% load static %}

    {% block body %}
                
            <div id="js-map" class="map"></div>
            <button id="dodaj_stanicu" class="btn btn-primary w-auto mt-3 ">Dodaj stanicu na mapi</button>
       
        <div id="forma" hidden="true" >
            <form  action="" method="post">
                {% csrf_token %} 
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" value="Sacuvaj">
            </form>
        </div>
        
    
    <div id="popup" class="ol-popup">
        <a href="#" id="popup-closer" class="ol-popup-closer"></a>
        <div id="popup-content"></div>
    </div>
    <div class="overlay-container">
        <span class="overlay-text" id="feature-name"></span><br>
        <span class="overlay-text" id="feature-additional-info"></span><br>

    </div>
    
    <script src="{% static 'mapa/main.js' %}"></script>
    <script>
        
      prikaziStanice('{% url "api:stanice" %}')
      document.getElementById('dodaj_stanicu').onclick = dodajStanicu 
      
    </script>
{% endblock %}

mapa/templates/mapa/linija.html
{% extends 'app/layout.html' %}
{% load static %}

{% block body %}
<h1>{{linija.naziv}}</h1>        
        <div id="js-map" class="map"></div> 
        <a class="btn btn-primary mt-2" href="{% url 'mapa:dodaj_liniju' %}">Dodaj novu liniju</a>

<div class="overlay-container">
    <span class="overlay-text" id="feature-name"></span><br>
    <span class="overlay-text" id="feature-additional-info"></span><br>

</div>
<script src="{% static 'mapa/main.js' %}"></script>
<script>
    
  prikaziStanice('{% url "api:linija" pk %}')
   
    
</script>
{% endblock %}